/**
 * Build-time script to generate mapbox.config.ts from environment variable.
 * 
 * Usage:
 *   MAPBOX_TOKEN=pk.xxx node scripts/set-env.js
 * 
 * Or create a .env file in the frontend/ directory:
 *   MAPBOX_TOKEN=pk.xxx
 * 
 * On Vercel, set MAPBOX_TOKEN in the project's Environment Variables.
 */
const fs = require('fs');
const path = require('path');

// Try to read from .env file if env var is not set
let token = process.env.MAPBOX_TOKEN || '';
if (!token) {
  const envPath = path.join(__dirname, '..', '.env');
  if (fs.existsSync(envPath)) {
    const envContent = fs.readFileSync(envPath, 'utf-8');
    const match = envContent.match(/^MAPBOX_TOKEN=(.+)$/m);
    if (match) token = match[1].trim();
  }
}

const outDir = path.join(__dirname, '..', 'src', 'app', 'config');
if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}

const content = `// AUTO-GENERATED by scripts/set-env.js — do not edit or commit
export const MAPBOX_TOKEN = '${token}';
`;

fs.writeFileSync(path.join(outDir, 'mapbox.config.ts'), content);
console.log(token
  ? '✓ mapbox.config.ts generated with token'
  : '⚠ mapbox.config.ts generated WITHOUT token (set MAPBOX_TOKEN env var)');

// ── Ensure Angular environment files exist (needed for fileReplacements) ──
const envDir = path.join(__dirname, '..', 'src', 'environments');
if (!fs.existsSync(envDir)) {
  fs.mkdirSync(envDir, { recursive: true });
}

const apiUrl = process.env.API_URL || 'https://smartitinery2-1.onrender.com/api';

const envDev = `export const environment = {
  production: false,
  apiUrl: '${apiUrl}',
};
`;

const envProd = `export const environment = {
  production: true,
  apiUrl: '${apiUrl}',
};
`;

const envDevPath = path.join(envDir, 'environment.ts');
const envProdPath = path.join(envDir, 'environment.prod.ts');

if (!fs.existsSync(envDevPath)) {
  fs.writeFileSync(envDevPath, envDev);
  console.log('✓ environment.ts created');
}
if (!fs.existsSync(envProdPath)) {
  fs.writeFileSync(envProdPath, envProd);
  console.log('✓ environment.prod.ts created');
}
